const CREATE_CHILD_CHAIN = '@@interbit/CREATE_CHILD_CHAIN'
const SPONSOR_CHAIN_REQUEST = '@@interbit/SPONSOR_CHAIN_REQUEST'
const SPONSOR_CHAIN = '@@interbit/SPONSOR_CHAIN'
const UPDATE_CONFIG = '@@interbit/UPDATE_CONFIG'
const MIGRATE = '@@interbit/MIGRATE'
const INIT = '@@interbit/INIT'
const SET_CHAIN_ID = '@@interbit/SET_CHAIN_ID'
const READ_JOIN_RESP = '@@interbit/READ_JOIN_RESP'
const FINISHED_READ_JOIN_ACTIONS = '@@interbit/FINISHED_READ_JOIN_ACTIONS'
const UPDATE_CHILDREN = '@@interbit/UPDATE_CHILDREN'
const INTERBIT_GET_STATE = '@@interbit/GET_STATE'
const DEPLOY_COVENANT = '@@interbit/DEPLOY_COVENANT'
const REMOVE_JOIN_CONFIG = '@@interbit/REMOVE_JOIN_CONFIG'
const SET_ACL = '@@interbit/SET_ACL'
const ADD_TO_ACL = '@@interbit/ADD_TO_ACL'
const AUTHORIZE_RECEIVE_ACTIONS = '@@interbit/AUTHORIZE_RECEIVE_ACTIONS'
const AUTHORIZE_SEND_ACTIONS = '@@interbit/AUTHORIZE_SEND_ACTIONS'
const DESTROY = '@@interbit/DESTROY'
const START_PROVIDE_STATE = '@@interbit/START_PROVIDE_STATE'
const START_CONSUME_STATE = '@@interbit/START_CONSUME_STATE'
const CONFIGURE_JOIN = '@@interbit/CONFIGURE_JOIN'
const REMOTE_REDISPATCH = '@@interbit/REMOTE_REDISPATCH'

const HYPERVISOR_BOOT = '*/HYPERVISOR_BOOT'
const HYPERVISOR_SHUTDOWN = '*/HYPERVISOR_SHUTDOWN'
const STROBE = '*/STROBE'

module.exports = {
  CREATE_CHILD_CHAIN,
  SPONSOR_CHAIN_REQUEST,
  SPONSOR_CHAIN,
  UPDATE_CONFIG,
  MIGRATE,
  INIT,
  SET_CHAIN_ID,
  READ_JOIN_RESP,
  FINISHED_READ_JOIN_ACTIONS,
  UPDATE_CHILDREN,
  INTERBIT_GET_STATE,
  STROBE,
  DEPLOY_COVENANT,
  REMOVE_JOIN_CONFIG,
  SET_ACL,
  ADD_TO_ACL,
  AUTHORIZE_RECEIVE_ACTIONS,
  AUTHORIZE_SEND_ACTIONS,
  DESTROY,
  START_PROVIDE_STATE,
  START_CONSUME_STATE,
  CONFIGURE_JOIN,
  REMOTE_REDISPATCH,
  HYPERVISOR_BOOT,
  HYPERVISOR_SHUTDOWN
}
